# Generated by Django 3.1.2 on 2020-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20200914_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(choices=[('Blusa de Moletom', 'Blusa de Moletom'), ('Calça de Sarja', 'Calça de Sarja'), ('Camisetas', 'Camisetas'), ('Bonés', 'Bonés'), ('Blusa corta-vento', 'Blusa corta-vento'), ('Calça de Moletom', 'Calça de Moletom'), ('Acessórios', 'Acessórios'), ('Jaquetas', 'Jaquetas'), ('Calçados', 'Calçados')], max_length=50, unique=True, verbose_name='Categoria')),
                ('slug', models.SlugField(unique=True)),
                ('foto_categoria', models.ImageField(blank=True, upload_to='fotos/categorias/%d/%m/%Y/')),
                ('publicada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
