# Generated by Django 3.1.2 on 2020-10-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria'),
        ('golden', '0022_auto_20201008_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_child', to='categorias.categoria'),
        ),
    ]
