# Generated by Django 3.1.2 on 2020-10-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_auto_20201008_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(choices=[('Acessorios', 'Acessorios'), ('Blusa Corta Vento', 'Blusa Corta Vento'), ('Blusa de Moletom', 'Blusa de Moletom'), ('Bonés', 'Bonés'), ('Calça de Moletom', 'Calça de Moletom'), ('Calçados', 'Calçados'), ('Calça de Sarja', 'Calça de Sarja'), ('Camisetas', 'Camisetas'), ('Jaquetas', 'Jaquetas')], max_length=50, unique=True, verbose_name='Categoria'),
        ),
    ]
