# Generated by Django 3.1.2 on 2020-10-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0006_remove_categoria_sub_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_child', to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(choices=[('Blusa de Moletom', 'Blusa de Moletom'), ('Calça de Sarja', 'Calça de Sarja'), ('Camisetas', 'Camisetas'), ('Bonés', 'Bonés'), ('Blusa corta-vento', 'Blusa corta-vento'), ('Calça de Moletom', 'Calça de Moletom'), ('Acessórios', 'Acessórios'), ('Jaquetas', 'Jaquetas'), ('Calçados', 'Calçados')], max_length=50, unique=True, verbose_name='Categoria'),
        ),
    ]
