# Generated by Django 3.1.2 on 2020-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_auto_20201009_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='sub_categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(choices=[('Acessórios', 'Acessórios'), ('Blusas', 'Blusas'), ('Bonés', 'Bonés'), ('Calças', 'Calças'), ('Camisetas', 'Camisetas'), ('Jaquetas', 'Jaquetas')], max_length=50, unique=True, verbose_name='Categoria'),
        ),
    ]
