# Generated by Django 3.1.2 on 2020-10-08 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria'),
        ('golden', '0021_auto_20200914_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('design_produto', models.TextField()),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tamanho_um', models.CharField(blank=True, default='P', max_length=5, verbose_name='Tamanhos')),
                ('tamanho_dois', models.CharField(blank=True, default='M', max_length=5, verbose_name='Tamanhos')),
                ('tamanho_tres', models.CharField(blank=True, default='G', max_length=5, verbose_name='Tamanhos')),
                ('tamanho_quatro', models.CharField(blank=True, default='GG', max_length=5, verbose_name='Tamanhos')),
                ('foto_produto', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('publicada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
