# Generated by Django 3.1.2 on 2020-10-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0022_auto_20201008_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
