# Generated by Django 3.1.2 on 2020-10-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0023_remove_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
