# Generated by Django 3.1.2 on 2020-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0024_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_dois',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_quatro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_tres',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_um',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='design_produto',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
