# Generated by Django 3.1.2 on 2020-10-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_auto_20201009_0008'),
        ('golden', '0025_auto_20201009_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', unique=True),
        ),
    ]
