# Generated by Django 3.1.2 on 2020-10-09 13:42

import categorias.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_auto_20201009_0008'),
        ('golden', '0026_auto_20201009_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=200, unique=True, verbose_name=categorias.models.Categoria),
        ),
    ]
