# Generated by Django 3.1.2 on 2020-10-09 13:42

import categorias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0027_auto_20201009_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=200, verbose_name=categorias.models.Categoria),
        ),
    ]
