# Generated by Django 3.1.2 on 2020-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0028_auto_20201009_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
