# Generated by Django 3.1.2 on 2020-10-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0030_pedido_pedidoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='golden.produto'),
            preserve_default=False,
        ),
    ]
