# Generated by Django 3.1.2 on 2020-10-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0031_pedido_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
    ]
