# Generated by Django 3.1.2 on 2020-10-28 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golden', '0032_remove_pedido_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduto',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
