# Generated by Django 3.1.2 on 2020-10-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0032_remove_pedido_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProduto',
        ),
    ]
