# Generated by Django 3.1.2 on 2020-10-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0036_remove_pedidoproduto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Carrinho', 'Carrinho'), ('Finalizado', 'Finalizado'), ('Pago', 'Pago'), ('Aguardando Pagamento', 'Aguardando Pagamento')], max_length=50, verbose_name='Status'),
        ),
    ]
