# Generated by Django 3.1.2 on 2020-11-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0037_auto_20201029_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
