# Generated by Django 3.1.2 on 2020-11-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0038_produto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduto',
            name='tamanho',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
