# Generated by Django 3.1.2 on 2020-11-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0040_pedidoproduto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='tamanho',
        ),
    ]
