# Generated by Django 3.1.2 on 2020-10-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201012_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='remote_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remote_receiver_id',
        ),
    ]
